datadir: "az://nf-blob-container/data"
refdir: "az://nf-blob-container/references"
bt2idx: "az://nf-blob-container/references/bt2idx"
outdir: "az://nf-blob-container/cutrun-results"
adapterpath: "./data"

genome: "az://nf-blob-container/references/Drosophila_melanogaster.BDGP6.dna.fa"
gtf: "az://nf-blob-container/references/Drosophila_melanogaster.BDGP6.85.sample.gtf"

reads: "az://nf-blob-container/data/*{1,2}.fq.gz"

threads: 4
illuminaclip: "ILLUMINACLIP:${params.adapterpath}/Truseq3.PE.fa:2:15:4:4:true"
leading: "LEADING:20"
trailing: "TRAILING:20"
slidingwindow: "SLIDINGWINDOW:4:15"
minlen: "MINLEN:25"

len: 99

idxname: "drosophila"
indexpath: "az://nf-blob-container/references/bt2idx"
